yaml
name: QA Approval Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  qa_approval:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: List changed files
        id: list_files
        run: echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"
        
      - name: Request QA Review
        id: request_qa_review
        uses: actions/github-script@v4
        with:
          script: |
            const files = "${{ steps.list_files.outputs.files }}".split('\n');
            const reviewers = ["baljeetio", "baljeetio"]; // Add your QA reviewers' usernames here
            
            const request = {
              reviewers: reviewers,
              title: 'QA Review Request',
              body: `Please review the changes in the following files:\n\n${files.join('\n')}`,
            };
            
            const response = await github.pulls.createReviewRequest(request);
            console.log(response);
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Merge to Production
        if: steps.request_qa_review.outputs.response
        run: |
          # Implement the merge to production here
          # This step will only run if the QA review request was successful
