name: Merge to Production after QA Approval

on:
  push:
    branches:
      - staging

jobs:
  merge_to_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Directory Contents
        run: |
          # List the contents of the directory you want to show to the QA approver
          ls -la 

      - name: Run QA Tests
        run: |
          # Run your QA tests on the contents of the directory
          # Replace the following line with your actual testing commands
          echo "Running QA tests..."

      - name: Check for QA Approval
        run: |
          # Specify the GitHub username of the QA approver
          QA_APPROVER="mejerrytech"
          
          # Get the username of the person who pushed the code
          PUSHED_BY=$(git log -1 ${{ github.sha }} --pretty=format:%an)

          if [ "$PUSHED_BY" == "$QA_APPROVER" ]; then
            echo "QA approval detected. Proceeding with the merge."
          else
            echo "QA approval not detected. Skipping the merge."
            exit 1
          fi

      - name: Merge to Production
        run: |
          # Merge staging into production
          git checkout production
          git merge staging --no-ff --no-edit
          # Push changes to production
          git push origin production
