name: QA Approval and Deployment

on:
  push:
    branches:
      - production
            
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!

  DeployProd:
    name: Deploy to Production 
    runs-on: ubuntu-latest
    environment: 
      name: Production
    steps:
      - name: Deploy
        run: echo I am deploying!         
